### ISSUE TITLE
class MobxComponent constructor and other issues

### ISSUE THREAD

**Issue by beckend** [xaviergonz/mobx-react-component#12]
```typescript
import { MobxComponent, mobxComponent } from 'mobx-react-component'

@mobxComponent({ refEmulation: false })
class SliderBase extends MobxComponent<any> {
  public s = {
    // throws, props is undefined
    max: this.props.max
    min: this.props.min
  }

  public constructor(props: any, context: any) {
    // typing states, that it does not accept arguments at all
    super(props. context)

   // this logs undefined, undefined
    console.log(props, context)
  }

  public render() {
    return null
  }
}
```

**Comment by xaviergonz** [comment]
That's because it is not actually a real class component, but a functional component with some "classy" things emulated to ease the transition to function components / make using mobx decorators easier, so it will only receive their first props on the first render.

instead of this:
```
public s = {
    // throws, props is undefined
    max: this.props.max
    min: this.props.min
  }
```

consider using this
```
render() {
  const min = useState(this.props.min)
  const max = useState(this.props.max)
}
```

or alternatively a lazy init
```
public s!: {max: number; min: number }

render() {
  if (!this.s) {
    this.s = {min: this.props.min, max: this.props.max}
  }
}
```

or this (not sure if the effect will run at this point or after the first render is finished though)
```
public s!: {max: number; min: number }

render() {
  useEffect(() => {
    this.s = {min: this.props.min, max: this.props.max}
  }, []); // componentDidMount equivalent
}
```

that being said, copying props into state is rarely a good idea
https://medium.com/@justintulk/react-anti-patterns-props-in-initial-state-28687846cc2e

**Comment by beckend** [comment]
well not really a bad pattern, it is more of a initialValues set at init, but why are we not using React.Component?

**Comment by beckend** [comment]
this kinda a turnoff when also the life-cycles are gone, i thought the purpose is to replace react component

**Comment by xaviergonz** [comment]
For real react class components you can just use mobx-react v5 (and up to some extent v6). The point of this library is to be able to use react functional components + hooks with mobx easily, while making the transition from react "style" components to functional component easier for old code-bases (or use the class alike style with decorators possible if that's more the user preference).

**Comment by beckend** [comment]
Alright thanks
